-- ============================================================================
-- SoftDesk 社区分享 · Phase 2 补丁: 埋点事件表 + 数据看板视图
-- 关联 PRD: .trae/documents/PRD-Community-Share.md
-- ============================================================================


-- ============================================================================
-- 1. share_events (埋点事件表)
-- 用途: 精细分析分享创建 → 复制 → 预览 → 导入 的完整漏斗
-- 与 shares.view_count / import_count 的差异:
--   - shares.* 是计数器 (轻量、无日志)
--   - share_events 是明细流水 (可分析时序、来源、用户维度)
-- ============================================================================

create table if not exists share_events (
  id                bigint generated by default as identity primary key,
  event_type        text not null
                    check (event_type in (
                      'share_create',
                      'share_copy',
                      'share_view',
                      'share_import_click',
                      'share_import_success',
                      'share_import_conflict',
                      'share_revoke',
                      'share_delete',
                      'share_report'
                    )),
  share_id          bigint references shares(id) on delete set null,
  share_token       text,
  actor_id          text,                                       -- 触发事件的用户 id, 可为 null (匿名预览)
  kind              text check (kind in ('workflow','favorite_group','radial')),
  meta              jsonb,                                      -- 事件附加信息 (如导入耗时、冲突类型)
  created_at        timestamptz not null default now()
);

create index if not exists idx_share_events_type_time
  on share_events(event_type, created_at desc);

create index if not exists idx_share_events_share_id
  on share_events(share_id);

create index if not exists idx_share_events_actor_id
  on share_events(actor_id)
  where actor_id is not null;


-- ============================================================================
-- 2. RLS: share_events
-- 策略: 任何人可写(前端主动上报), 只有事件当事人 / 分享 owner 可读
-- ============================================================================

alter table share_events enable row level security;

-- 策略 1: 允许匿名 / 登录用户 insert 事件
drop policy if exists "anyone insert share events" on share_events;
create policy "anyone insert share events"
  on share_events
  for insert
  with check (true);

-- 策略 2: 用户可读自己作为 actor 的事件
-- 用 Supabase Auth 原生 auth.uid() (与 shares/share_imports 保持一致)
drop policy if exists "actor read own share events" on share_events;
create policy "actor read own share events"
  on share_events
  for select
  using (
    actor_id is not null
    and auth.uid()::text = actor_id
  );

-- 策略 3: 分享 owner 可读自己分享下所有事件 (看板要用)
drop policy if exists "owner read share events" on share_events;
create policy "owner read share events"
  on share_events
  for select
  using (
    exists (
      select 1 from shares
      where shares.id = share_events.share_id
        and auth.uid()::text = shares.owner_id
    )
  );


-- ============================================================================
-- 3. 数据看板视图: share_funnel_daily
-- 用途: 每日分享漏斗 (创建 → 预览 → 导入点击 → 导入成功)
-- 查询示例:  select * from share_funnel_daily order by day desc limit 14;
-- ============================================================================

create or replace view share_funnel_daily as
select
  date_trunc('day', created_at)::date         as day,
  count(*) filter (where event_type = 'share_create')          as creates,
  count(*) filter (where event_type = 'share_copy')            as copies,
  count(*) filter (where event_type = 'share_view')            as views,
  count(distinct share_token) filter (where event_type = 'share_view') as unique_views,
  count(*) filter (where event_type = 'share_import_click')    as import_clicks,
  count(*) filter (where event_type = 'share_import_success')  as import_success,
  count(*) filter (where event_type = 'share_import_conflict') as import_conflict,
  count(*) filter (where event_type = 'share_report')          as reports
from share_events
group by 1
order by 1 desc;


-- ============================================================================
-- 4. 数据看板视图: share_top_creators
-- 用途: 分享贡献者 Top 榜, 用于社区激励参考
-- ============================================================================

create or replace view share_top_creators as
select
  s.owner_id,
  s.owner_nickname,
  count(*)                                            as share_count,
  coalesce(sum(s.view_count), 0)::bigint              as total_views,
  coalesce(sum(s.import_count), 0)::bigint            as total_imports,
  max(s.created_at)                                   as last_shared_at
from shares s
where s.is_revoked = false and s.is_archived = false
group by s.owner_id, s.owner_nickname
order by total_imports desc, total_views desc;


-- ============================================================================
-- 5. 验证
-- ============================================================================
-- 执行完成后, 在 Supabase 里应该能看到:
--   表:  share_events
--   视图: share_funnel_daily, share_top_creators
-- 试写一条测试事件:
--   insert into share_events(event_type) values ('share_create');
--   select * from share_funnel_daily;
-- ============================================================================
