-- ============================================================================
-- SoftDesk 社区分享功能 - 数据库建表脚本
-- 文档版本: v1.0
-- 关联 PRD: .trae/documents/PRD-Community-Share.md
--
-- 执行方式: 在 Supabase SQL Editor 中依次执行下列 SQL
-- 前置依赖: 已存在 workflows / favorites / favorite_groups / radial_configs 表
-- ============================================================================


-- ============================================================================
-- 1. shares (分享主表)
-- ============================================================================

create table if not exists shares (
  id                bigint generated by default as identity primary key,
  share_token       text not null unique,                          -- nanoid(10) 短码
  owner_id          text not null,                                 -- 分享者 user_id
  owner_nickname    text,                                          -- 冗余: 分享者昵称快照
  kind              text not null
                    check (kind in ('workflow','favorite_group','radial')),
  title             text not null check (char_length(title) <= 50),
  description       text check (description is null or char_length(description) <= 200),
  payload           jsonb not null,                                -- 内容快照, 上限 100KB
  view_count        integer not null default 0,
  import_count      integer not null default 0,
  report_count      integer not null default 0,
  is_public         boolean not null default true,                 -- 预留: 广场公开开关
  is_revoked        boolean not null default false,                -- 撤销标记
  is_archived       boolean not null default false,                -- 归档标记 (180 天无访问)
  expires_at        timestamptz,                                   -- 可选过期时间
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  -- payload 大小硬约束 (~100KB)
  constraint payload_size_limit
    check (octet_length(payload::text) <= 102400)
);

-- 索引: 按 owner 查询"我的分享"
create index if not exists idx_shares_owner_id
  on shares(owner_id)
  where is_revoked = false and is_archived = false;

-- 索引: 按 token 查询预览 (最常用)
create index if not exists idx_shares_token_active
  on shares(share_token)
  where is_revoked = false and is_archived = false;

-- 索引: 归档定时任务扫描
create index if not exists idx_shares_updated_at
  on shares(updated_at)
  where is_archived = false;


-- ============================================================================
-- 2. share_imports (导入记录表)
-- ============================================================================

create table if not exists share_imports (
  id                bigint generated by default as identity primary key,
  share_id          bigint not null references shares(id) on delete cascade,
  importer_id       text not null,                                 -- 导入者 user_id
  imported_at       timestamptz not null default now(),
  unique(share_id, importer_id)                                    -- 防重复计数
);

create index if not exists idx_share_imports_share_id
  on share_imports(share_id);

create index if not exists idx_share_imports_importer_id
  on share_imports(importer_id);


-- ============================================================================
-- 3. share_reports (举报表)
-- ============================================================================

create table if not exists share_reports (
  id                bigint generated by default as identity primary key,
  share_id          bigint not null references shares(id) on delete cascade,
  reporter_id       text,                                          -- 举报者 user_id, 可空匿名
  reason            text not null check (char_length(reason) <= 200),
  created_at        timestamptz not null default now()
);

create index if not exists idx_share_reports_share_id
  on share_reports(share_id);


-- ============================================================================
-- 4. 触发器: 累计举报 >= 3 自动撤销
-- ============================================================================

create or replace function fn_auto_revoke_on_reports()
returns trigger
language plpgsql
security definer
as $$
begin
  update shares
    set report_count = report_count + 1,
        is_revoked   = case when report_count + 1 >= 3 then true else is_revoked end,
        updated_at   = now()
    where id = new.share_id;
  return new;
end;
$$;

drop trigger if exists trg_shares_auto_revoke on share_reports;
create trigger trg_shares_auto_revoke
  after insert on share_reports
  for each row execute function fn_auto_revoke_on_reports();


-- ============================================================================
-- 5. 触发器: 自动维护 updated_at
-- ============================================================================

create or replace function fn_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_shares_touch_updated_at on shares;
create trigger trg_shares_touch_updated_at
  before update on shares
  for each row execute function fn_touch_updated_at();


-- ============================================================================
-- 6. RPC: 原子递增 view_count (防并发丢失更新)
-- ============================================================================

create or replace function increment_share_view(p_token text)
returns void
language plpgsql
security definer
as $$
begin
  update shares
    set view_count = view_count + 1
    where share_token = p_token
      and is_revoked = false
      and is_archived = false
      and (expires_at is null or expires_at > now());
end;
$$;


-- ============================================================================
-- 7. RPC: 原子递增 import_count (仅在首次导入时调用)
-- ============================================================================

create or replace function increment_share_import(p_share_id bigint)
returns void
language plpgsql
security definer
as $$
begin
  update shares
    set import_count = import_count + 1
    where id = p_share_id;
end;
$$;


-- ============================================================================
-- 8. RPC: 归档 180 天无访问的分享 (供定时任务调用)
-- ============================================================================

create or replace function archive_stale_shares()
returns integer
language plpgsql
security definer
as $$
declare
  affected integer;
begin
  update shares
    set is_archived = true
    where is_archived = false
      and updated_at < now() - interval '180 days';
  get diagnostics affected = row_count;
  return affected;
end;
$$;


-- ============================================================================
-- 9. RLS: shares 表
-- ============================================================================

alter table shares enable row level security;

-- 策略 1: 匿名可读未撤销、未归档、未过期的分享 (预览页免登录)
drop policy if exists "public read active shares" on shares;
create policy "public read active shares"
  on shares
  for select
  using (
    is_revoked = false
    and is_archived = false
    and (expires_at is null or expires_at > now())
  );

-- 策略 2: owner 可管理自己的所有分享 (含撤销/归档的)
drop policy if exists "owner manage own shares" on shares;
create policy "owner manage own shares"
  on shares
  for all
  using (owner_id = current_setting('app.current_user_id', true))
  with check (owner_id = current_setting('app.current_user_id', true));


-- ============================================================================
-- 10. RLS: share_imports 表
-- ============================================================================

alter table share_imports enable row level security;

-- 策略 1: 用户只可读自己的导入记录
drop policy if exists "user read own imports" on share_imports;
create policy "user read own imports"
  on share_imports
  for select
  using (importer_id = current_setting('app.current_user_id', true));

-- 策略 2: 用户只可插入自己的导入记录
drop policy if exists "user insert own imports" on share_imports;
create policy "user insert own imports"
  on share_imports
  for insert
  with check (importer_id = current_setting('app.current_user_id', true));

-- 策略 3: owner 可读到自己分享被谁导入 (统计"我的分享"数据)
drop policy if exists "owner read imports of own shares" on share_imports;
create policy "owner read imports of own shares"
  on share_imports
  for select
  using (
    exists (
      select 1 from shares
      where shares.id = share_imports.share_id
        and shares.owner_id = current_setting('app.current_user_id', true)
    )
  );


-- ============================================================================
-- 11. RLS: share_reports 表
-- ============================================================================

alter table share_reports enable row level security;

-- 策略 1: 匿名/登录用户均可插入举报 (预览页免登录也能举报)
drop policy if exists "anyone insert reports" on share_reports;
create policy "anyone insert reports"
  on share_reports
  for insert
  with check (true);

-- 策略 2: 举报人只可读自己的举报
drop policy if exists "reporter read own reports" on share_reports;
create policy "reporter read own reports"
  on share_reports
  for select
  using (
    reporter_id is not null
    and reporter_id = current_setting('app.current_user_id', true)
  );


-- ============================================================================
-- 12. 验证
-- ============================================================================
-- 执行完成后, 在 Supabase Table Editor 中应看到:
--   - shares
--   - share_imports
--   - share_reports
-- 且三张表的 RLS 状态均已开启 (锁标)
-- ============================================================================
