-- ============================================================================
-- SoftDesk 产品分析事件表
-- 用途: 记录最小化的产品使用行为, 仅用于功能使用率 / 成功率 / 版本分布分析
-- 隐私原则:
--   - 不记录账号 ID, 邮箱, 昵称
--   - 不记录搜索词, 软件名, 路径, 工作流名等自由文本
--   - 仅使用匿名安装标识
--   - 事件类型和 meta 键受白名单约束
-- ============================================================================

create table if not exists product_events (
  id              bigint generated by default as identity primary key,
  install_id      text not null,
  event_type      text not null
                  check (event_type in (
                    'app_first_open',
                    'scan_completed',
                    'software_launch',
                    'workflow_created',
                    'workflow_launched',
                    'favorite_toggled',
                    'radial_opened',
                    'radial_launch',
                    'ai_suggestion_used',
                    'ai_search_used',
                    'share_create',
                    'share_copy',
                    'share_view',
                    'share_import_click',
                    'share_import_success',
                    'share_import_conflict',
                    'share_revoke',
                    'share_delete',
                    'share_report'
                  )),
  result          text not null default 'success'
                  check (result in ('success', 'failed', 'skipped')),
  duration_bucket text,
  feature_category text,
  platform        text,
  os_version      text,
  app_version     text,
  locale          text,
  meta            jsonb,
  created_at      timestamptz not null default now()
);

create index if not exists idx_product_events_type_time
  on product_events(event_type, created_at desc);

create index if not exists idx_product_events_install_id
  on product_events(install_id)
  where install_id is not null;

-- 限制 meta 大小, 防止无限膨胀
alter table product_events
  add constraint product_events_meta_size
  check (meta is null or octet_length(meta::text) <= 2048);

-- 事件类型 + 特性类别联合长度限制
alter table product_events
  add constraint product_events_type_length
  check (char_length(event_type) <= 40);

alter table product_events
  add constraint product_events_category_length
  check (feature_category is null or char_length(feature_category) <= 32);

alter table product_events
  add constraint product_events_install_id_length
  check (char_length(install_id) between 16 and 64);

alter table product_events enable row level security;

-- 匿名写入: 任何持有 anon key 的客户端都可以写入(这是埋点的特性)
-- 但通过 CHECK 约束和白名单限制了可写入字段的范围
drop policy if exists "anon insert product events" on product_events;
create policy "anon insert product events"
  on product_events
  for insert
  to anon
  with check (true);

drop policy if exists "authenticated insert product events" on product_events;
create policy "authenticated insert product events"
  on product_events
  for insert
  to authenticated
  with check (true);

-- 禁止客户端读取: 埋点数据只能后台分析
drop policy if exists "anon select product events" on product_events;
drop policy if exists "authenticated select product events" on product_events;

-- 保留期策略建议:
--   - 原始 product_events 保留 90 天
--   - 每日聚合表保留 18 个月
-- 需配合定时任务或 pg_cron 实现, 此处仅记录规范
